# Generated by Django 4.2.23 on 2025-08-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_employeetask_task_end_date_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_detail', models.JSONField(default=list)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.employeetask')),
            ],
        ),
    ]
