# Generated by Django 4.2.23 on 2025-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.JSONField(default=list),
        ),
    ]
