# Generated by Django 4.2.23 on 2025-08-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='attendance',
            new_name='attendance_detail',
        ),
    ]
