# Generated by Django 4.2.23 on 2025-08-31 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_attendance_user_attendance_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Massage',
        ),
    ]
