# Generated by Django 4.2.23 on 2025-08-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_massage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attendance_detail',
        ),
    ]
