# Generated by Django 4.2.23 on 2025-08-21 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_date', models.DateTimeField(null=True)),
                ('task_end_date', models.DateTimeField(null=True)),
                ('task_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.managertask')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
