# Generated by Django 4.2.23 on 2025-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='task_end_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='task_start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
