# Generated by Django 4.2.23 on 2025-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_employeetask_task_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='task_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='task_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
