# Generated by Django 4.2.23 on 2025-08-31 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0005_project_massage_managertask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeetask',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='employeetask',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='managertask',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='massage',
            old_name='employee_task_id',
            new_name='employee_task',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_detail', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
