# Generated by Django 4.2.23 on 2025-09-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_rename_task_id_employeetask_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeetask',
            old_name='task',
            new_name='manager_task',
        ),
    ]
